"""Event embdeddings

Revision ID: 960af8e5c7b5
Revises: dcefbdf2f6e1
Create Date: 2025-05-23 10:32:06.590862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960af8e5c7b5'
down_revision = 'dcefbdf2f6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
