"""Adjust embedding dim for local model

Revision ID: e4ab6030d8f4
Revises: 960af8e5c7b5
Create Date: 2025-05-27 13:20:17.206034

"""
import pgvector
from alembic import op
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'e4ab6030d8f4'
down_revision = '960af8e5c7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)

    # ### end Alembic commands ###
