"""Removed index for embeddings

Revision ID: ebd66b30005a
Revises: e4ab6030d8f4
Create Date: 2025-05-29 12:55:40.659084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd66b30005a'
down_revision = 'e4ab6030d8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_embedding'), postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_embedding'), ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    # ### end Alembic commands ###
